- name: Update apt cache
  apt:
    update_cache: yes
- name: Install Git 
  apt: 
    name: git
    state: present

- name: Install prerequisites
  apt:
    name:
      - software-properties-common
      - curl
      - git
      - python3-pymysql
    state: present

- name: Add PHP PPA
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP 8.2 and extensions
  apt:
    name:
      - php8.2
      - libapache2-mod-php8.2
      - php8.2-mysql
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-zip
      - php8.2-curl
      - php8.2-gd

    state: present

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Install Composer
  shell: |
    curl -sS https://getcomposer.org/installer | php
    mv composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: Create Laravel directory structure
  file:
    path: "{{ laravel_dir }}/public"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Copy Apache virtual host configuration
  template:
    src: laravel.conf.j2
    dest: /etc/apache2/sites-available/laravel.conf
    mode: "0644"

- name: Enable Laravel virtual host
  command: a2ensite laravel.conf
  args:
    creates: /etc/apache2/sites-enabled/laravel.conf

- name: Disable default virtual host
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf

- name: Restart Apache2
  service:
    name: apache2
    state: restarted
